name: Docker Image CI - dotnet-api-template

on: push

env:
  APP_NAME: dotnet-api-template

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print status
      run: echo "Building $APP_NAME"
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/$APP_NAME:latest
